	<header class="clearfix">
		<div class="contenedor">
			<a href="../index.html">
				<img src="../../img/logoIGEVET.png" alt="logo"/>
			</a>
			<nav>
				<ul id="menu">
					<li><a href="../../institucional.html">Institucional</a></li>
					<li><a href="../../lineas.html">Líneas</a></li>
					<li><a href="../../servicios.html">Servicios</a></li>
					<li><a href="../../eventos.html">Eventos</a></li>
					<li><a href="../../contacto.html">Contacto</a></li>
				</ul>
			</nav>
		</div>
	</header>