	<section class="anclaje">
		<div class="contenedor">
			<div class="datos">
				<p>Av. 60 y 119 s/n - La Plata</p>
				<p>Tel.: +54 (0221) 4211799</p>
				<p>E-mail: secretaria@igevet.gob.ar</p>
			</div>
			<div class="contexto">
				<ul>
					<li><img src="../../img/conicet_negro.png" alt="conicet"></li>
					<li><img src="../../img/fcv.png" alt="facultad de ciencias veterinarias"></li>
					<li><img src="../../img/unlp.png" alt="universidad nacional de la plata"></li>
				</ul>
			</div>
		</div>
		<div class="cleaner"></div>
	</section>
	<div class="cleaner"></div>
	<footer>
		<div class="contenedor">
			<ul>
				<li><a href="../institucional.html">Institucional</a></li>
				<li><a href="../lineas.html">Líneas</a></li>
				<li><a href="../servicios.html">Servicios</a></li>
				<li><a href="../eventos.html">Eventos</a></li>
				<li><a href="../contacto.html">Contacto</a></li>
			</ul>
			<p>copyright 2015 IGEVET - Todos los derechos reservados</p>
		</div>
	</footer>
</body>
</html>