	<section>
		<div class="contenedor">
			<div class="bloqueb"></div>
			<div class="cleaner"></div>
		</div>
	</section>
	<section class="anclaje">
		<div class="contenedor">
			<div class="datos">
				<ul>
					<li><p>Av. 60 y 118 s/n - La Plata</p></li>
					<li><p>Tel.: +54 (0221) 4211799</p></li>
					<li><p>E-mail: secretaria@igevet.gob.ar</p></li>
				</ul>
			</div>
			<div  class="contexto">
				<img src="../../img/ancla.png" alt="instituciones"></li>
					
			</div>
		
		</div class="cleaner"></div>
	</section>
	<footer>
		<div class="contenedor">
			<p>copyright 2015 IGEVET - Todos los derechos reservados</p>
		</div>
	</footer>
</body>
</html>