<!DOCTYPE html>
<html lang="es">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
		<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
		<!-- <title>IGEVET - Servicios - Corrección y revisión de textos científicos. Traducción</title> -->
		<meta name="description" content="Instituto de Genética Veterinaria Ing. Fernando Noel Dulout">
		<meta name="keywords" content="genética, veterinaria, microarrays, abigeato, genotipificación, secuenciación, radiación, efectos ionizantes, carcinogenesis, mutagenesis, carnicerias saludables, equinos">
		<meta name="authors" content="estudio feather">
		<meta rel="icon" href="../../img/icon_igevet.png" type="image/x-icon"/>
		<link rel="shortcut icon" href="../../img/icon_igevet.png" type="image/x-icon"/>
		<link href='http://fonts.googleapis.com/css?family=Lato:400,300,400italic,700,300italic' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" type="text/css" href="../../css/reset.css"/>
		<link rel="stylesheet" type="text/css" href="../../css/estilos.css"/>
		<script src="../js/modernizr.custom.js"></script>

		<!--menu responsive-->
		<link rel="stylesheet" href="../../css/slicknav.css">

		<script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.6.2/modernizr.min.js"></script>
		<script src="../js/jquery.min.js"></script>
		<script src="../js/jquery.slicknav.js"></script>
		<script type="text/javascript">
		$(document).ready(function(){
			$('#menu').slicknav();
		});
		</script>
</head>